apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app-name hola-mundio
spec:
  selector:
    matchLabels:
      app: *app-name
  replicas: 3
  template:
    metadata:
      labels:
        app: *app-name
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
